package org.chain.demo.demomybatis.mapper;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.chain.demo.demomybatis.model.Family;
import org.chain.demo.demomybatis.model.FamilyExample;

import java.util.List;

public interface FamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    long countByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    int deleteByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    @Delete({
        "delete from family",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    @Insert({
        "insert into family (name, identity_id, ",
        "gender, birthday, ",
        "tel, address, salary, ",
        "remark, create_time, ",
        "update_time)",
        "values (#{name,jdbcType=VARCHAR}, #{identityId,jdbcType=VARCHAR}, ",
        "#{gender,jdbcType=INTEGER}, #{birthday,jdbcType=TIMESTAMP}, ",
        "#{tel,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, #{salary,jdbcType=BIGINT,typeHandler=org.chain.demo.demomybatis.handler.MoneyTypeHandler}, ",
        "#{remark,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    int insertSelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    List<Family> selectByExampleWithRowbounds(FamilyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    List<Family> selectByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    @Select({
        "select",
        "id, name, identity_id, gender, birthday, tel, address, salary, remark, create_time, ",
        "update_time",
        "from family",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("org.chain.demo.demomybatis.mapper.FamilyMapper.BaseResultMap")
    Family selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") Family record, @Param("example") FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    int updateByExample(@Param("record") Family record, @Param("example") FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    int updateByPrimaryKeySelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    @Update({
        "update family",
        "set name = #{name,jdbcType=VARCHAR},",
          "identity_id = #{identityId,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=INTEGER},",
          "birthday = #{birthday,jdbcType=TIMESTAMP},",
          "tel = #{tel,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "salary = #{salary,jdbcType=BIGINT,typeHandler=org.chain.demo.demomybatis.handler.MoneyTypeHandler},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Family record);
}