package org.chain.demo.demomybatis.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.joda.money.Money;

import java.io.Serializable;
import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Family implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.id
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.name
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.identity_id
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String identityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.gender
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.birthday
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.tel
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.address
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.salary
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private Money salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.remark
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.create_time
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.update_time
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.id
     *
     * @return the value of family.id
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.id
     *
     * @param id the value for family.id
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.name
     *
     * @return the value of family.name
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.name
     *
     * @param name the value for family.name
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.identity_id
     *
     * @return the value of family.identity_id
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public String getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withIdentityId(String identityId) {
        this.setIdentityId(identityId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.identity_id
     *
     * @param identityId the value for family.identity_id
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setIdentityId(String identityId) {
        this.identityId = identityId == null ? null : identityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.gender
     *
     * @return the value of family.gender
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withGender(Integer gender) {
        this.setGender(gender);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.gender
     *
     * @param gender the value for family.gender
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.birthday
     *
     * @return the value of family.birthday
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withBirthday(Date birthday) {
        this.setBirthday(birthday);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.birthday
     *
     * @param birthday the value for family.birthday
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.tel
     *
     * @return the value of family.tel
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withTel(String tel) {
        this.setTel(tel);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.tel
     *
     * @param tel the value for family.tel
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.address
     *
     * @return the value of family.address
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withAddress(String address) {
        this.setAddress(address);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.address
     *
     * @param address the value for family.address
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.salary
     *
     * @return the value of family.salary
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Money getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withSalary(Money salary) {
        this.setSalary(salary);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.salary
     *
     * @param salary the value for family.salary
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setSalary(Money salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.remark
     *
     * @return the value of family.remark
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.remark
     *
     * @param remark the value for family.remark
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.create_time
     *
     * @return the value of family.create_time
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.create_time
     *
     * @param createTime the value for family.create_time
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.update_time
     *
     * @return the value of family.update_time
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public Family withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.update_time
     *
     * @param updateTime the value for family.update_time
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", identityId=").append(identityId);
        sb.append(", gender=").append(gender);
        sb.append(", birthday=").append(birthday);
        sb.append(", tel=").append(tel);
        sb.append(", address=").append(address);
        sb.append(", salary=").append(salary);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}