package org.chain.demo.demomybatis.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * @author renchen
 * @date 2019-11-16 16:46
 **/
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FamilyDto implements Serializable {
    private static final long serialVersionUID = 5160657033418192512L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.id
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.name
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.identity_id
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String identityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.gender
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.birthday
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.tel
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.address
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.salary
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private BigDecimal salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.remark
     *
     * @mbg.generated Sat Nov 16 14:57:14 CST 2019
     */
    private String remark;
}
